
Vagrant.configure("2") do |config|
  config.vm.box = "chad-thompson/ubuntu-trusty64-gui"
  config.vm.synced_folder "shared", "/temp/shared"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
    vb.cpus=2
  end

  config.vm.define "VagrantVM" do |tibz|
    tibz.vm.hostname = "tibzie"
    tibz.vm.provision "shell", path: "script.sh"
  end


end
