
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
    vb.cpus=2
  end

  config.vm.define "VagrantVM" do |spidey|
  	spidey.vm.hostname = "spidey.vagrant"
  	spidey.vm.provision "shell", inline: "echo 'updating packages'"
  	spidey.vm.provision "shell", inline: "sudo apt-get update"
  	spidey.vm.provision "shell", inline: "echo 'installing Unity interface!'"
  	spidey.vm.provision "shell", inline: "sudo apt-get install -y ubuntu-desktop"
  end
end
